const data = {
    Section4data: [
        {
            id: 1,
            tag: "Hot",
            product: "images/product-1-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$28.85",
            del: "32.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 2,
            tag: "Sale",
            product: "images/product-2-1.jpg",
            title: "Hodo food",
            details: "All natural italian-style Chicken Meatballs",
            image: "images/star.png",
            rating: "(3.5)",
            sponser: "By",
            food: "Stoffer",
            price: "$52.85",
            del: "85.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 3,
            tag: "New",
            product: "images/product-3-1.jpg",
            title: "Snack",
            details: "Angie's Boomchickapop sweet & salty kettle corn",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "StarKist",
            price: "$48.85",
            del: "52.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 4,
            tag: "",
            product: "images/product-4-1.jpg",
            title: "Vagetables",
            details: "Faster farms takeout crispy classic buffalowings",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$17.85",
            del: "19.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 5,
            tag: "-14%",
            product: "images/product-5-1.jpg",
            title: "Hodo Food",
            details: "Chobani complete vanilla greek yogurt",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$23.85",
            del: "25.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 6,
            tag: "",
            product: "images/product-6-1.jpg",
            title: "Meats",
            details: "Canada dry ginger ale-2L bottle-200ml -400gm",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$54.85",
            del: "55.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 7,
            tag: "Sale",
            product: "images/product-7-1.jpg",
            title: "Snack",
            details: "Encore seafoods stuffed alaskan salmon",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$32.85",
            del: "33.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 8,
            tag: "Sale",
            product: "images/product-8-1.jpg",
            title: "Coffee",
            details: "Gortan's beer battered fish fillets with soft paper",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$35.85",
            del: "37.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 9,
            tag: "Sale",
            product: "images/product-9-1.jpg",
            title: "Cream",
            details: "Haagen-dazs caramel cone ice cream ketchup",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Old EI Peso",
            price: "$23.85",
            del: "35.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 10,
            tag: "",
            product: "images/product-10-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
    ],
    Section5data: [
        {
            id: 1,
            tag: "Hot",
            product: "images/product-1-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$28.85",
            del: "32.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 2,
            tag: "Sale",
            product: "images/product-2-1.jpg",
            title: "Hodo food",
            details: "All natural italian-style Chicken Meatballs",
            image: "images/star.png",
            rating: "(4.5)",
            sponser: "By",
            food: "Stoffer",
            price: "$52.85",
            del: "85.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 3,
            tag: "New",
            product: "images/product-3-1.jpg",
            title: "Snack",
            details: "Angie's Boomchickapop sweet & salty kettle corn",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "StarKist",
            price: "$48.85",
            del: "52.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 4,
            tag: "-14%",
            product: "images/product-5-1.jpg",
            title: "Hodo Food",
            details: "Chobani complete vanilla greek yogurt",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$23.85",
            del: "25.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
    ],


    Shopdata: [
        {
            id: 1,
            tag: "Hot",
            product: "images/product-1-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$28.85",
            del: "32.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 2,
            tag: "Sale",
            product: "images/product-2-1.jpg",
            title: "Hodo food",
            details: "All natural italian-style Chicken Meatballs",
            image: "images/star.png",
            rating: "(3.5)",
            sponser: "By",
            food: "Stoffer",
            price: "$52.85",
            del: "85.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 3,
            tag: "New",
            product: "images/product-3-1.jpg",
            title: "Snack",
            details: "Angie's Boomchickapop sweet & salty kettle corn",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "StarKist",
            price: "$48.85",
            del: "52.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 4,
            tag: "",
            product: "images/product-4-1.jpg",
            title: "Vagetables",
            details: "Faster farms takeout crispy classic buffalowings",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$17.85",
            del: "19.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 5,
            tag: "-14%",
            product: "images/product-5-1.jpg",
            title: "Hodo Food",
            details: "Chobani complete vanilla greek yogurt",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$23.85",
            del: "25.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 6,
            tag: "Sale",
            product: "images/product-6-1.jpg",
            title: "Meats",
            details: "Canada dry ginger ale-2L bottle-200ml -400gm",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$54.85",
            del: "55.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 7,
            tag: "New",
            product: "images/product-7-1.jpg",
            title: "Snack",
            details: "Encore seafoods stuffed alaskan salmon",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$32.85",
            del: "33.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 8,
            tag: "Sale",
            product: "images/product-8-1.jpg",
            title: "Coffee",
            details: "Gortan's beer battered fish fillets with soft paper",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Nestfood",
            price: "$35.85",
            del: "37.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 9,
            tag: "Hot",
            product: "images/product-9-1.jpg",
            title: "Cream",
            details: "Haagen-dazs caramel cone ice cream ketchup",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Old EI Peso",
            price: "$23.85",
            del: "35.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 10,
            tag: "New",
            product: "images/product-10-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 11,
            tag: "Hot",
            product: "images/product-3-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 12,
            tag: "Sale",
            product: "images/product-7-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 13,
            tag: "New",
            product: "images/product-9-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 14,
            tag: "Hot",
            product: "images/product-1-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 15,
            tag: "-14%",
            product: "images/product-2-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
        {
            id: 16,
            tag: "Sale",
            product: "images/product-6-1.jpg",
            title: "Snack",
            details: "seeds of change organic quinoa brown,& red rice",
            image: "images/star.png",
            rating: "(4.0)",
            sponser: "By",
            food: "Tyson",
            price: "$22.85",
            del: "24.8",
            pic: "images/icon-cart.png",
            add: "Add"
        },
    ]

}
export default data;